### ISSUE TITLE
RGB-D + LiDAR SLAM

### ISSUE THREAD

**Issue by kdhRGT** [sunsided/RoboND-MapMyWorld#2]
Hello sir

I checked your launch file,

it looks like you only use the rgb-d camera for SLAM

Am I right?

if it is true, then did you try to perform RGB-D + LiDAR SLAM for rtabmap?

best regards

**Comment by sunsided** [comment]
Heya! I might have misunderstood, but RGB-D is color + depth, so it actually _is_ LiDAR.

**Comment by kdhRGT** [comment]
Oh hello thx for reply

I saw your demo video, I am not sure but the robot looks like it has a 2d lidar also.

did you use it for rtabmap slam?

or do you just only consider using an RGB-D camera?

best regards

**Comment by sunsided** [comment]
Hehe, yep, this project only uses the RGB-D camera to obtain the distance information. I think using multiple RGB-D cameras is probably beneficial over a spinning laser LiDAR simply because of versatility (and practically maintenance costs), so I would likely only consider RGB-D and/or "stereo" RGB myself.

**Comment by kdhRGT** [comment]
thank you so much to reply :)

it was very helpful!

best regards
